In [1]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))
from shared.collect_data import DataCollector
from shared.clean_data import DataCleaning
import ta

# Data Collection

In [2]:
data_collector = DataCollector(
    symbol = "BTC/USDT", 
    timeframe = "5m", 
    days = 365,
    limit = 1000
)
df = data_collector.collect_data()

In [3]:
df.head()

            timestamp      open      high       low     close    volume
0 2024-05-27 04:00:00  68873.43  68901.74  68840.16  68846.68  29.78123
1 2024-05-27 04:05:00  68846.69  68855.74  68804.00  68804.00  30.22310
2 2024-05-27 04:10:00  68804.01  68862.08  68804.00  68824.31  64.10034
3 2024-05-27 04:15:00  68824.31  68824.32  68794.98  68822.87  22.77996
4 2024-05-27 04:20:00  68822.87  68865.83  68822.86  68841.40  65.28963

In [4]:
df.describe()

,timestamp,open,high,low,close,volume
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,99.588242
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,113.215420
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,5471.439430
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,139.580703

# Clean Data

In [5]:
clean_data = DataCleaning(
    df=df,
)

df = clean_data.clean_data()

In [6]:
df.describe()

,timestamp,open,high,low,close,volume
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544

# Technical Indicators

### Momentum Indicators

#### <font color="#5283fe">Awesome Oscillator (AO)</font>
###### The Awesome Oscillator is an indicator used to measure market momentum. AO calculates the difference of a 34 Period and 5 Period Simple Moving Averages. The Simple Moving Averages that are used are not calculated using closing price but rather each bar’s midpoints. AO is generally used to affirm trends or to anticipate possible reversals.

In [7]:
df["AO"] = ta.momentum.AwesomeOscillatorIndicator(
    high=df["high"],
    low=df["low"],
    window1=5,
    window2=34
).awesome_oscillator()

df.describe()

,timestamp,open,high,low,close,volume,AO
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602

#### <font color="#5283fe">Kaufman’s Adaptive Moving Average (KAMA)</font>
###### Moving average designed to account for market noise or volatility. KAMA will closely follow prices when the price swings are relatively small and the noise is low. KAMA will adjust when the price swings widen and follow prices from a greater distance. This trend-following indicator can be used to identify the overall trend, time turning points and filter price movements.

In [8]:
df["KAMA"] = ta.momentum.KAMAIndicator(close=df['close']).kama()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037

#### <font color="#5283fe">Percentage Price Oscillator (PPO)</font>
###### is a momentum oscillator that measures the difference between two moving averages as a percentage of the larger moving average.

In [21]:
ppo = ta.momentum.PercentagePriceOscillator(
    close=df['close'],
    window_slow=26,
    window_fast=12,
    window_sign=9
)

df["PPO"] = ppo.ppo()

df["PPO_HIST"] = ppo.ppo_hist()

df["PPO_SIGNAL"] = ppo.ppo_signal()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI,STOCH_RSI,STOCH_OSC,STOCH_OSC_SIGNAL,TSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000,105094.000000,105107.000000,105105.000000,105083.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696,0.501520,51.207062,51.207292,0.787425
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526,0.000000,0.000000,0.000000,-70.563083
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211,0.165259,25.268436,26.373259,-11.715909
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209,0.502881,51.740250,51.670470,1.020195
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786,0.839065,77.410300,76.193698,13.368256
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451,1.000000,100.000000,100.000000,74.403186
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923,0.357306,29.751276,27.510894,18.419441

#### <font color="#5283fe">Percentage Volume Oscillator (PVO)</font>
###### is a momentum oscillator for volume. The PVO measures the difference between two volume-based moving averages as a percentage of the larger moving average.

In [22]:
pvo = ta.momentum.PercentageVolumeOscillator(
    volume =df['volume'],
    window_slow=26,
    window_fast=12,
    window_sign=9
)

df["PVO"] = pvo.pvo()

df["PVO_HIST"] = pvo.pvo_hist()

df["PVO_SIGNAL"] = pvo.pvo_signal()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI,STOCH_RSI,STOCH_OSC,STOCH_OSC_SIGNAL,TSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000,105094.000000,105107.000000,105105.000000,105083.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696,0.501520,51.207062,51.207292,0.787425
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526,0.000000,0.000000,0.000000,-70.563083
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211,0.165259,25.268436,26.373259,-11.715909
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209,0.502881,51.740250,51.670470,1.020195
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786,0.839065,77.410300,76.193698,13.368256
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451,1.000000,100.000000,100.000000,74.403186
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923,0.357306,29.751276,27.510894,18.419441

#### <font color="#5283fe">Rate of Change (ROC)</font>
###### The Rate-of-Change (ROC) indicator, which is also referred to as simply Momentum, is a pure momentum oscillator that measures the percent change in price from one period to the next. The ROC calculation compares the current price with the price “n” periods ago. The plot forms an oscillator that fluctuates above and below the zero line as the Rate-of-Change moves from positive to negative. As a momentum oscillator, ROC signals include centerline crossovers, divergences and overbought-oversold readings.

In [14]:
df["ROC"] = ta.momentum.ROCIndicator(
    close=df['close'],
    window=12
).roc()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908

#### <font color="#5283fe">Relative Strength Index (RSI)</font>
###### Compares the magnitude of recent gains and losses over a specified time period to measure speed and change of price movements of a security. It is primarily used to attempt to identify overbought or oversold conditions in the trading of an asset.

In [15]:
df["RSI"] = ta.momentum.RSIIndicator(close=df['close'], window=14).rsi()
df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923

#### <font color="#5283fe">Stochastic RSI</font>
###### The StochRSI oscillator was developed to take advantage of both momentum indicators in order to create a more sensitive indicator that is attuned to a specific security’s historical performance rather than a generalized analysis of price change.

In [17]:
df["STOCH_RSI"] = ta.momentum.StochRSIIndicator(
    close=df['close'],
    window=14,
    smooth1=3,
    smooth2=3
).stochrsi()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI,STOCH_RSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000,105094.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696,0.501520
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526,0.000000
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211,0.165259
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209,0.502881
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786,0.839065
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451,1.000000
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923,0.357306

#### <font color="#5283fe">Stochastic Oscillator</font>
###### Developed in the late 1950s by George Lane. The stochastic oscillator presents the location of the closing price of a stock in relation to the high and low range of the price of a stock over a period of time, typically a 14-day period.

In [23]:
stoch = ta.momentum.StochasticOscillator(
    high=df['high'],
    low=df['low'],
    close=df['close'],
    window=14,
    smooth_window=3
)

df["STOCH_OSC"] = stoch.stoch()

df["STOCH_OSC_SIGNAL"] = stoch.stoch_signal()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI,STOCH_RSI,STOCH_OSC,STOCH_OSC_SIGNAL,TSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000,105094.000000,105107.000000,105105.000000,105083.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696,0.501520,51.207062,51.207292,0.787425
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526,0.000000,0.000000,0.000000,-70.563083
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211,0.165259,25.268436,26.373259,-11.715909
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209,0.502881,51.740250,51.670470,1.020195
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786,0.839065,77.410300,76.193698,13.368256
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451,1.000000,100.000000,100.000000,74.403186
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923,0.357306,29.751276,27.510894,18.419441

#### <font color="#5283fe">True strength index (TSI)</font>
###### Shows both trend direction and overbought/oversold conditions.

In [20]:
df["TSI"] = ta.momentum.TSIIndicator(
    close=df['close'],
    window_slow=25,
    window_fast=13
).tsi()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA,PPO,PPO_HIST,PPO_SIGNAL,PVO,PVO_HIST,PVO_SIGNAL,ROC,RSI,STOCH_RSI,STOCH_OSC,STOCH_OSC_SIGNAL,TSI
count,105120,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105087.000000,105111.000000,105095.000000,105087.000000,105087.000000,105095.000000,105087.000000,105087.000000,105108.000000,105107.000000,105094.000000,105107.000000,105105.000000,105083.000000
mean,2024-11-25 15:57:29.999999488,80223.130309,80298.325966,80146.671418,80223.510718,71.610843,5.526587,80219.637966,0.002788,0.000005,0.002790,-1.377218,0.000049,-1.377430,0.006703,50.386696,0.501520,51.207062,51.207292,0.787425
min,2024-05-27 04:00:00,49351.260000,49966.620000,49000.000000,49338.490000,1.755100,-3567.873088,50687.935750,-1.916957,-0.622071,-1.608772,-52.207390,-19.508577,-48.369820,-7.348482,8.474526,0.000000,0.000000,0.000000,-70.563083
25%,2024-08-26 09:58:45,64098.460000,64136.660000,64050.000000,64098.450000,32.478160,-136.602956,64113.936616,-0.068071,-0.023302,-0.064296,-9.880013,-4.171663,-8.279274,-0.218650,43.098211,0.165259,25.268436,26.373259,-11.715909
50%,2024-11-25 15:57:30,82973.645000,83051.825000,82885.285000,82973.645000,59.132620,9.313059,82972.193060,0.005181,-0.000406,0.005095,-1.784759,-0.736480,-1.348414,0.006984,50.571209,0.502881,51.740250,51.670470,1.020195
75%,2025-02-24 21:56:15,96165.025000,96232.002500,96093.352500,96165.080000,99.588242,153.331515,96160.507836,0.078995,0.023346,0.074935,6.406674,3.289511,5.234118,0.236274,57.736786,0.839065,77.410300,76.193698,13.368256
max,2025-05-27 03:55:00,111924.070000,111980.000000,111812.420000,111924.080000,234.292130,4895.497941,111640.246496,1.823188,0.678299,1.701378,59.275105,50.151671,38.656686,7.057981,93.901451,1.000000,100.000000,100.000000,74.403186
std,NaN,16620.771008,16636.206820,16604.755069,16620.969847,49.362544,362.401602,16620.750037,0.176298,0.052706,0.166165,12.394032,6.302687,10.196433,0.540908,10.956923,0.357306,29.751276,27.510894,18.419441