In [10]:
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))
from shared.collect_data import DataCollector
from shared.clean_data import DataCleaning
import ta

# Data Collection

In [2]:
data_collector = DataCollector(
    symbol = "BTC/USDT", 
    timeframe = "5m", 
    days = 365,
    limit = 1000
)
df = data_collector.collect_data()

In [3]:
df.head()

            timestamp      open      high       low     close    volume
0 2024-05-26 02:50:00  68904.01  68920.00  68894.43  68919.98   8.05561
1 2024-05-26 02:55:00  68919.99  68935.25  68900.00  68904.01  43.19788
2 2024-05-26 03:00:00  68904.00  68937.44  68894.00  68908.42  22.49785
3 2024-05-26 03:05:00  68908.41  68928.59  68880.60  68928.59  29.70913
4 2024-05-26 03:10:00  68928.58  68962.57  68928.58  68962.56   9.81436

In [4]:
df.describe()

,timestamp,open,high,low,close,volume
count,105121,105121.000000,105121.000000,105121.000000,105121.000000,105121.000000
mean,2024-11-24 14:49:59.999999744,80107.064334,80182.131282,80030.734149,80107.448540,99.558411
min,2024-05-26 02:50:00,49351.260000,49966.620000,49000.000000,49338.490000,0.948920
25%,2024-08-25 08:50:00,64098.610000,64136.660000,64050.000000,64098.600000,32.471450
50%,2024-11-24 14:50:00,82835.990000,82930.880000,82747.030000,82836.010000,59.109740
75%,2025-02-23 20:50:00,96102.240000,96181.810000,96018.690000,96102.620000,113.180650
max,2025-05-26 02:50:00,111924.070000,111980.000000,111812.420000,111924.080000,5471.439430
std,NaN,16557.556891,16573.147048,16541.382334,16557.766511,139.567612

# Clean Data

In [5]:
clean_data = DataCleaning(
    df=df,
)

df = clean_data.clean_data()

In [7]:
df.describe()

,timestamp,open,high,low,close,volume
count,105121,105121.000000,105121.000000,105121.000000,105121.000000,105121.000000
mean,2024-11-24 14:49:59.999999744,80107.064334,80182.131282,80030.734149,80107.448540,71.576456
min,2024-05-26 02:50:00,49351.260000,49966.620000,49000.000000,49338.490000,0.948920
25%,2024-08-25 08:50:00,64098.610000,64136.660000,64050.000000,64098.600000,32.471450
50%,2024-11-24 14:50:00,82835.990000,82930.880000,82747.030000,82836.010000,59.109740
75%,2025-02-23 20:50:00,96102.240000,96181.810000,96018.690000,96102.620000,99.558411
max,2025-05-26 02:50:00,111924.070000,111980.000000,111812.420000,111924.080000,234.234590
std,NaN,16557.556891,16573.147048,16541.382334,16557.766511,49.331287

# Technical Indicators

### Momentum Indicators

#### <font color="#5283fe">Awesome Oscillator (AO)</font>
###### The Awesome Oscillator is an indicator used to measure market momentum. AO calculates the difference of a 34 Period and 5 Period Simple Moving Averages. The Simple Moving Averages that are used are not calculated using closing price but rather each bar’s midpoints. AO is generally used to affirm trends or to anticipate possible reversals.

In [29]:
df["AO"] = ta.momentum.AwesomeOscillatorIndicator(
    high=df["high"],
    low=df["low"],
    window1=5,
    window2=34
).awesome_oscillator()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA
count,105121,105121.000000,105121.000000,105121.000000,105121.000000,105121.000000,105088.000000,105112.000000
mean,2024-11-24 14:49:59.999999744,80107.064334,80182.131282,80030.734149,80107.448540,71.576456,5.584734,80103.509110
min,2024-05-26 02:50:00,49351.260000,49966.620000,49000.000000,49338.490000,0.948920,-3567.873088,50687.935750
25%,2024-08-25 08:50:00,64098.610000,64136.660000,64050.000000,64098.600000,32.471450,-136.601816,64113.946546
50%,2024-11-24 14:50:00,82835.990000,82930.880000,82747.030000,82836.010000,59.109740,9.257559,82855.182666
75%,2025-02-23 20:50:00,96102.240000,96181.810000,96018.690000,96102.620000,99.558411,153.265846,96090.336741
max,2025-05-26 02:50:00,111924.070000,111980.000000,111812.420000,111924.080000,234.234590,4895.497941,111640.246496
std,NaN,16557.556891,16573.147048,16541.382334,16557.766511,49.331287,362.285377,16557.411095

#### <font color="#5283fe">Kaufman’s Adaptive Moving Average (KAMA)</font>
###### Moving average designed to account for market noise or volatility. KAMA will closely follow prices when the price swings are relatively small and the noise is low. KAMA will adjust when the price swings widen and follow prices from a greater distance. This trend-following indicator can be used to identify the overall trend, time turning points and filter price movements.

In [28]:
df["KAMA"] = ta.momentum.KAMAIndicator(close=df['close']).kama()

df.describe()

,timestamp,open,high,low,close,volume,AO,KAMA
count,105121,105121.000000,105121.000000,105121.000000,105121.000000,105121.000000,105088.000000,105112.000000
mean,2024-11-24 14:49:59.999999744,80107.064334,80182.131282,80030.734149,80107.448540,71.576456,5.584734,80103.509110
min,2024-05-26 02:50:00,49351.260000,49966.620000,49000.000000,49338.490000,0.948920,-3567.873088,50687.935750
25%,2024-08-25 08:50:00,64098.610000,64136.660000,64050.000000,64098.600000,32.471450,-136.601816,64113.946546
50%,2024-11-24 14:50:00,82835.990000,82930.880000,82747.030000,82836.010000,59.109740,9.257559,82855.182666
75%,2025-02-23 20:50:00,96102.240000,96181.810000,96018.690000,96102.620000,99.558411,153.265846,96090.336741
max,2025-05-26 02:50:00,111924.070000,111980.000000,111812.420000,111924.080000,234.234590,4895.497941,111640.246496
std,NaN,16557.556891,16573.147048,16541.382334,16557.766511,49.331287,362.285377,16557.411095